import { Ticket, AnalyticsData, DisseminationItem, GanttTask, TeamMember } from './types';

export const AUTH_CREDENTIALS = {
  username: 'Admin123',
  password: 'admin123'
};

export const TEAM_MEMBERS: TeamMember[] = [
  { id: '1', name: 'Nancy Madera', roles: [], workPackages: [], country: 'Argentina', institution: 'Universidad Nacional de San Martín', email: 'nanmadera@gmail.com', initials: 'NM' },
  { id: '2', name: 'Carolina Coll', roles: [], workPackages: [], country: 'Brazil', institution: 'Universidade Federal de Pelotas', email: 'ccoll@equidade.org', initials: 'CC' },
  { id: '3', name: 'Franciele Hellwig', roles: [], workPackages: [], country: 'Brazil', institution: 'Universidade Federal de Pelotas', email: 'fhellwig@equidade.org', initials: 'FH' },
  { id: '4', name: 'Franciele Leite', roles: [], workPackages: [], country: 'Brazil', institution: 'Universidade Federal do Espírito Santo', email: 'test@me.com', initials: 'FL' },
  { id: '5', name: 'Deborah Malta', roles: [], workPackages: [], country: 'Brazil', institution: 'Universidade Federal de Minas Gerais', email: 'dcmalta@uol.com.br', initials: 'DM' },
  { id: '6', name: 'Franciele Marabotti', roles: [], workPackages: [], country: 'Brazil', institution: 'Federal University of Espírito Santo', email: 'francielemarabotti@gmail.com', initials: 'FM' },
  { id: '7', name: 'Beverley Essue', roles: [], workPackages: [], country: 'Canada', institution: 'University of Toronto', email: 'beverley.essue@utoronto.ca', initials: 'BE' },
  { id: '8', name: 'Heidi Stöckl', roles: [], workPackages: [], country: 'Germany', institution: 'Ludwig Maximilian University of Munich', email: 'heidi.stoeckl@ibe.med.uni-muenchen.de', initials: 'HS' },
  { id: '9', name: 'Merike Blofield', roles: [], workPackages: [], country: 'Germany', institution: 'University of Hamburg', email: 'merike.blofield@uni-hamburg.de', initials: 'MB' },
  { id: '10', name: 'Anil Kumar', roles: [], workPackages: [], country: 'India', institution: 'Public Health Foundation India', email: 'anil.kumar@phfi.org', initials: 'AK' },
  { id: '11', name: 'Neha Dhole', roles: [], workPackages: [], country: 'India', institution: 'Public Health Foundation India', email: 'neha.dhole@phfi.org', initials: 'ND' },
  { id: '12', name: 'Rakhi Dandona', roles: [], workPackages: [], country: 'India', institution: 'University of Washington', email: 'rdandona@uw.edu', initials: 'RD' },
  { id: '13', name: 'Nata Duvvury', roles: [], workPackages: [], country: 'Ireland', institution: 'University of Galway', email: 'nata.duvvury@nuigalway.ie', initials: 'ND' },
  { id: '14', name: 'David Contreras Loya', roles: [], workPackages: [], country: 'Mexico', institution: 'Tecnológico de Monterrey', email: 'd.contreras@tec.mx', initials: 'DCL' },
  { id: '15', name: 'Renzo Calderon-Anyosa', roles: [], workPackages: [], country: 'Peru', institution: 'Universidad Peruana Cayetano Heredia', email: 'renzo.calderon.anyosa@gmail.com', initials: 'RCA' },
  { id: '16', name: 'Shanaaz Mathews', roles: [], workPackages: [], country: 'South Africa', institution: 'University of Cape Town', email: 'shanaaz.mathews@uct.ac.za', initials: 'SM' },
  { id: '17', name: 'Aislinn Delany', roles: [], workPackages: [], country: 'South Africa', institution: 'University of Cape Town', email: 'aislinn.delany@gmail.com', initials: 'AD' },
  { id: '18', name: 'Lillian Artz', roles: [], workPackages: [], country: 'South Africa', institution: 'University of Cape Town', email: 'lillian.artz@uct.ac.za', initials: 'LA' },
  { id: '19', name: 'Benita Moolman', roles: [], workPackages: [], country: 'South Africa', institution: 'University of Cape Town', email: 'benita.moolman@uct.ac.za', initials: 'BM' },
  { id: '20', name: 'Phiwe Nota', roles: [], workPackages: [], country: 'South Africa', institution: 'University of Cape Town', email: 'phiwe.nota@uct.ac.za', initials: 'PN' },
  { id: '21', name: 'Athraa Fakier', roles: [], workPackages: [], country: 'South Africa', institution: 'University of Cape Town', email: 'athraa.fakier@uct.ac.za', initials: 'AF' },
  { id: '22', name: 'Rajendra Surenthirakumaran', roles: [], workPackages: [], country: 'Sri Lanka', institution: 'University of Jaffna', email: 'surenthirakumaran@gmail.com', initials: 'RS' },
  { id: '23', name: 'Pethirupillai Coonghe', roles: [], workPackages: [], country: 'Sri Lanka', institution: 'University of Jaffna', email: 'padcoonghe@gmail.com', initials: 'PC' },
  { id: '24', name: 'Subaschandren Kumaran', roles: [], workPackages: [], country: 'Sri Lanka', institution: 'University of Jaffna', email: 's.kumaran3@gmail.com', initials: 'SK' },
  { id: '25', name: 'Fazla Fayaz', roles: [], workPackages: [], country: 'Sri Lanka', institution: 'University of Jaffna', email: 'f.f.ahamedfayaz@bham.ac.uk', initials: 'FF' },
  { id: '26', name: 'Asvini Fernando', roles: [], workPackages: [], country: 'Sri Lanka', institution: 'University of Kelaniya', email: 'asvinif@gmail.com', initials: 'AF' },
  { id: '27', name: 'Shivany Shanmugathas', roles: [], workPackages: [], country: 'Sri Lanka', institution: 'University of Jaffna', email: 'test@me.com', initials: 'SS' },
  { id: '28', name: 'Nethanjalie Mapitigama', roles: [], workPackages: [], country: 'Sri Lanka', institution: 'Ministry of Health, Sri Lanka', email: 'test@me.com', initials: 'NM' },
  { id: '29', name: 'Asiri Hewamalage', roles: [], workPackages: [], country: 'Sri Lanka', institution: 'Ministry of Health, Sri Lanka', email: 'asiri11@yahoo.com', initials: 'AH' },
  { id: '30', name: 'Kumudu Wijewardene', roles: [], workPackages: [], country: 'Sri Lanka', institution: 'Sabaragamuwa University of Sri Lanka', email: 'kumuduwije@gmail.com', initials: 'KW' },
  { id: '31', name: 'Dinesh Coonghe', roles: [], workPackages: [], country: 'Sri Lanka', institution: 'University of Jaffna', email: 'padcoonghe@gmail.com', initials: 'DC' },
  { id: '32', name: 'Pirasanth Paskaran', roles: [], workPackages: [], country: 'Sri Lanka', institution: 'University of Jaffna', email: 'paskaranpirasanth@gmail.com', initials: 'PP' },
  { id: '33', name: 'Nethanjalie Mapitigama (2)', roles: [], workPackages: [], country: 'Sri Lanka', institution: 'Ministry of Health, Sri Lanka', email: 'nethmap@hotmail.com', initials: 'NM' },
  { id: '34', name: 'Joht Singh Chandan', roles: [], workPackages: [], country: 'UK', institution: 'University of Birmingham', email: 'j.s.chandan.1@bham.ac.uk', initials: 'JSC' },
  { id: '35', name: 'Krishnarajah Nirantharakumar', roles: [], workPackages: [], country: 'UK', institution: 'Kings College London', email: 'k.nirantharan@bham.ac.uk', initials: 'KN' },
  { id: '36', name: 'Siddartha Bandyopadhyay', roles: [], workPackages: [], country: 'UK', institution: 'University of Birmingham', email: 's.bandyopadhyay@bham.ac.uk', initials: 'SB' },
  { id: '37', name: 'Tiffany Gooden', roles: [], workPackages: [], country: 'UK', institution: 'Kings College London', email: 'g.tiffany@bham.ac.uk', initials: 'TG' },
  { id: '38', name: 'lllin Gani', roles: [], workPackages: [], country: 'UK', institution: 'University of Birmingham', email: 'ixg162@student.bham.ac.uk', initials: 'IG' },
  { id: '39', name: 'Jaya Nambiar', roles: [], workPackages: [], country: 'UK', institution: 'University of Birmingham', email: 'j.nambiar@bham.ac.uk', initials: 'JN' },
  { id: '40', name: 'Dmitri Nepogodiev', roles: [], workPackages: [], country: 'UK', institution: 'University of Birmingham', email: 'd.nepogodiev@bham.ac.uk', initials: 'DN' },
  { id: '41', name: 'Gene Feder', roles: [], workPackages: [], country: 'UK', institution: 'University of Bristol', email: 'Gene.Feder@bristol.ac.uk', initials: 'GF' },
  { id: '42', name: 'Julie Taylor', roles: [], workPackages: [], country: 'UK', institution: 'University of Birmingham', email: 'j.taylor.1@bham.ac.uk', initials: 'JT' },
  { id: '43', name: 'Caroline Bradbury-Jones', roles: [], workPackages: [], country: 'UK', institution: 'University of Birmingham', email: 'c.bradbury-jones@bham.ac.uk', initials: 'CBJ' },
  { id: '44', name: 'Jacky Mulveen', roles: [], workPackages: [], country: 'UK', institution: 'WE:ARE', email: 'jacky@weareuk.org', initials: 'JM' },
  { id: '45', name: 'Priyanka Sharma', roles: [], workPackages: [], country: 'UK', institution: 'University of Birmingham', email: 'p.k.sharma@bham.ac.uk', initials: 'PS' },
  { id: '46', name: 'Siddhartha Bandyopadhyay (2)', roles: [], workPackages: [], country: 'UK', institution: 'University of Birmingham', email: 's.bandyopadhyay@bham.ac.uk', initials: 'SB' },
  { id: '47', name: 'Abigail Bull', roles: [], workPackages: [], country: 'UK', institution: 'NIHR', email: 'abigail.bull@nihr.ac.uk', initials: 'AB' },
  { id: '48', name: 'Emmanuela Gakidou', roles: [], workPackages: [], country: 'USA', institution: 'University of Washington', email: 'gakidou@uw.edu', initials: 'EG' },
  { id: '49', name: 'Nicholas Metheny', roles: [], workPackages: [], country: 'USA', institution: 'Emory University', email: 'nick.metheny@emory.edu', initials: 'NM' },
  { id: '50', name: 'Felicia Knaul', roles: [], workPackages: [], country: 'USA', institution: 'University of Miami', email: 'fknaul@miami.edu', initials: 'FK' },
  { id: '51', name: 'Caroline Stein', roles: [], workPackages: [], country: 'USA', institution: 'University of Washington', email: 'cstein87@uw.edu', initials: 'CS' },
  { id: '52', name: 'Cory Spencer', roles: [], workPackages: [], country: 'USA', institution: 'University of Washington', email: 'corycns@uw.edu', initials: 'CS' },
  { id: '53', name: 'Jack Cagney', roles: [], workPackages: [], country: 'USA', institution: 'University of Washington', email: 'jcagney@uw.edu', initials: 'JC' },
  { id: '54', name: 'Eleanor Jane Hepburn', roles: [], workPackages: [], country: 'Global', institution: 'Independent / Consultant', email: 'hepburn.eleanorjane@gmail.com', initials: 'EJH' },
  { id: '55', name: 'Flavia Bustreo', roles: [], workPackages: [], country: 'Global', institution: 'Independent / WHO', email: 'flaviabustreo@gmail.com', initials: 'FB' },
];


export const MOCK_TICKETS: Ticket[] = [
  {
    id: 'ticket_1',
    no: '1.04',
    date: '02/06/2026',
    ticketInfo: 'Send team governance sheet ',
    owners: ['Illin Gani'],
    owner: 'Illin Gani',
    action: '-IG to send out to. country leads',
    status: 'To Do',
    completedDate: '',
    deadline: '',
    comments: '',
    category: 'Project_admin',
    isCore: false,
    isArchived: false,
  },
  {
    id: 'ticket_2',
    no: '1.04',
    date: '02/06/2026',
    ticketInfo: 'WP2 Survey Design ',
    owners: ['p.k.sharma@bham.ac.uk', 'Priyanka Sharma'],
    owner: 'Priyanka Sharma',
    action: '- PS setup meeting with gene feder, Heidi stokl ',
    status: 'In Progress',
    completedDate: '',
    deadline: '',
    comments: '[02/06/2026 14:32] ',
    category: 'WP2',
    isCore: false,
    isArchived: false,
  },
  {
    id: 'ticket_3',
    no: '6.01',
    date: '02/06/2026',
    ticketInfo: 'David touchbase',
    owners: ['Nick Methany', 'Joht Singh Chandan', 'p.k.sharma@bham.ac.uk', 'Illin Gani', 'Priyanka Sharma'],
    owner: 'Nick Methany',
    action: '- NM to check with David if available for Monday meeting',
    status: 'To Do',
    completedDate: '',
    deadline: '',
    comments: '[30/06/2026 14:09] - David internal meetings, wait tomorrow, concerns around changes with governance structure - schedule meeting for friday ',
    category: 'Project_admin',
    isCore: false,
    isArchived: false,
  },
  {
    id: 'ticket_4',
    no: '1.01',
    date: '01/06/2026',
    ticketInfo: 'WP1: Workshop series 3 ',
    owners: ['Nick Methany', 'Illin Gani'],
    owner: 'Nick Methany',
    action: '- IG, NM and Benita carry out workshop series 1',
    status: 'Completed',
    completedDate: '16/06/2026',
    deadline: '',
    comments: '[01/06/2026 10:17] \nCountry Updates on WP1\nStatus - Ethics Application Processes and Approvals for Survivor Panels\nChallenges experienced\nWorkshop in September',
    category: 'WP1',
    isCore: false,
    isArchived: false,
  },
  {
    id: 'ticket_5',
    no: '1.05',
    date: '12/06/2026',
    ticketInfo: 'Set up meet with Shiv and SM/JC re: ToR',
    owners: [],
    owner: '',
    action: '',
    status: 'To Do',
    completedDate: '',
    deadline: '',
    comments: '',
    category: 'Project_admin',
    isCore: false,
    isArchived: false,
  },
  {
    id: 'ticket_6',
    no: '1.04',
    date: '02/06/2026',
    ticketInfo: 'Monthly bulletin ',
    owners: ['p.k.sharma@bham.ac.uk', 'Illin Gani'],
    owner: 'Priyanka Sharma',
    action: '',
    status: 'To Do',
    completedDate: '',
    deadline: '',
    comments: '[02/06/2026 14:28] - Links to website, work done across countries.',
    category: 'Project_admin',
    isCore: false,
    isArchived: false,
  },
  {
    id: 'ticket_7',
    no: '1.04',
    date: '02/06/2026',
    ticketInfo: 'WP5 hub ',
    owners: ['Illin Gani'],
    owner: 'Illin Gani',
    action: '- IG to progress ',
    status: 'To Do',
    completedDate: '',
    deadline: '',
    comments: '[02/06/2026 14:30] \nfeatures: \n-> communal repo -> literature library \n-> webinars \n\n',
    category: 'Project_admin',
    isCore: false,
    isArchived: false,
  },
  {
    id: 'ticket_8',
    no: '1.04',
    date: '12/06/2026',
    ticketInfo: 'Meeting with Bev withJC, SM and NM',
    owners: [],
    owner: '',
    action: '-PS to chase up JSC',
    status: 'To Do',
    completedDate: '',
    deadline: '',
    comments: '[30/06/2026 14:25] - bev okay with meeting including Nata\nDiscuss WP3 ',
    category: 'WP1',
    isCore: false,
    isArchived: false,
  },
  {
    id: 'ticket_9',
    no: '1.04',
    date: '02/06/2026',
    ticketInfo: 'NIHR Report in July ',
    owners: ['Priyanka Sharma'],
    owner: 'Priyanka Sharma',
    action: '- PS compile 6-month progress report',
    status: 'To Do',
    completedDate: '',
    deadline: '01/07/2026',
    comments: '[30/06/2026 14:17] - 6th July, ',
    category: 'Project_admin',
    isCore: false,
    isArchived: false,
  },
  {
    id: 'ticket_10',
    no: '1.03',
    date: '02/06/2026',
    ticketInfo: 'WP1 workshop: series 4',
    owners: ['Illin Gani', 'Nick Methany'],
    owner: 'Illin Gani',
    action: '- IG setup meeting in 3rd august 12pm UK time',
    status: 'In Progress',
    completedDate: '',
    deadline: '',
    comments: '',
    category: 'WP1',
    isCore: false,
    isArchived: false,
  },
  {
    id: 'ticket_11',
    no: '1.05',
    date: '12/06/2026',
    ticketInfo: 'Sep meeting planning - each country representative',
    owners: [],
    owner: '',
    action: '',
    status: 'To Do',
    completedDate: '',
    deadline: '',
    comments: '',
    category: 'WP1',
    isCore: false,
    isArchived: false,
  },
  {
    id: 'ticket_12',
    no: '1.02',
    date: '01/06/2026',
    ticketInfo: 'Funding release',
    owners: ['Illin Gani', 'Priyanka Sharma', 'Joht Singh Chandan'],
    owner: 'Illin Gani',
    action: '',
    status: 'Completed',
    completedDate: '02/06/2026',
    deadline: '',
    comments: '[01/06/2026 11:52] WP1 series 3',
    category: 'WP1',
    isCore: true,
    isArchived: false,
  },
  {
    id: 'ticket_13',
    no: '1.01',
    date: '01/06/2026',
    ticketInfo: 'Sri Lanka - ERC application for Work Package 2 of the Violence Against Women study',
    owners: ['Illin Gani', 'Joht Singh Chandan'],
    owner: 'Illin Gani',
    action: '- IG to fill in details and complete the sections relating to your professional\n- JSC signature',
    status: 'Completed',
    completedDate: '01/06/2026',
    deadline: '',
    comments: '',
    category: 'WP2',
    isCore: true,
    isArchived: false,
  }
];

export const MOCK_ANALYTICS: AnalyticsData[] = [
  { platform: 'Facebook', spend: 450, clicks: 1200, engagement: 3500, completions: 85, adDays: 14, date: '2026-03-01', notes: 'Targeting urban areas' },
  { platform: 'Instagram', spend: 320, clicks: 850, engagement: 5200, completions: 62, adDays: 10, date: '2026-03-05', notes: 'High engagement on stories' },
  { platform: 'Twitter/X', spend: 150, clicks: 400, engagement: 1200, completions: 18, adDays: 7, date: '2026-03-10', notes: 'Niche professional audience' },
  { platform: 'Facebook', spend: 580, clicks: 1500, engagement: 4200, completions: 112, adDays: 14, date: '2026-03-15', notes: 'Optimized creative' },
  { platform: 'TikTok', spend: 200, clicks: 900, engagement: 8500, completions: 45, adDays: 5, date: '2026-03-20', notes: 'Younger demographic focus' },
];

export const MOCK_GANTT_TASKS: GanttTask[] = [];

export const MOCK_DISSEMINATION: DisseminationItem[] = [
  {
    id: 'd1',
    title: 'Effects of interventional public health laws and regulations intended to reduce gambling-related harms: a realist review study protocol',
    summary: 'BMJ Open (2025) - This protocol sets out the methods for a realist review that will synthesise evidence on how laws and regulations intended to reduce gambling harms work (or don’t), for whom, and in what contexts, including potential unintended effects and equity impacts.',
    links: [{ label: 'BMJ Open', url: 'https://bmjopen.bmj.com/content/15/7/e093906' }],
    date: '2025-07-01',
    type: 'Publication'
  },
  {
    id: 'd2',
    title: 'Legal and regulatory responses to online gambling harms: a scoping review of evidence',
    summary: 'Harm Reduction Journal (2025) - This scoping review maps evidence on (1) the distinct challenges of regulating online gambling and (2) the evidence on legal/regulatory interventions intended to reduce online gambling harms. It identifies major evidence gaps, including limited evaluation of impacts across population subgroups and a tendency toward individual-level rather than systems approaches in the literature.',
    links: [{ label: 'Harm Reduction Journal', url: 'https://link.springer.com/article/10.1186/s12954-025-01292-y' }],
    date: '2025-01-15',
    type: 'Publication'
  },
  {
    id: 'd3',
    title: 'High stakes: does the gambling White Paper go far enough?',
    summary: 'The Lancet (2024) — Comment/debate (short correspondence-style piece) - This short piece responds to the UK Government’s gambling White Paper, considering whether the proposed reforms are likely to be sufficient from a public health and health inequalities perspective. It highlights the importance of evaluating how regulatory changes affect harms across different population groups, and the need for stronger evidence on what legal and regulatory interventions achieve in practice.',
    links: [{ label: 'The Lancet', url: 'https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(23)01914-1/fulltext' }],
    date: '2024-05-20',
    type: 'Publication'
  },
  {
    id: 'd4',
    title: 'Gambling Control in a Cost-of-Living Crisis: An Analysis of the White Paper High Stakes: Gambling Reform for the Digital Age (2023)',
    summary: 'Modern Law Review (2024) - This peer-reviewed article provides a detailed academic analysis of the UK Government’s White Paper High Stakes: Gambling Reform for the Digital Age (2023). It explains the context and key proposals of the White Paper, focusing on efforts to reduce gambling-related harms and on the implications of mandated affordability checks for online gambling. The article situates regulatory reform within broader debates about consumer protection, surveillance, and public health.',
    links: [{ label: 'Modern Law Review', url: 'https://onlinelibrary-wiley-com.bham-ezproxy.idm.oclc.org/doi/pdf/10.1111/1468-2230.1290' }],
    date: '2024-03-10',
    type: 'Publication'
  },
  {
    id: 'd5',
    title: 'Effects of interventional public health laws and regulations intended to reduce gambling-related harms',
    summary: 'Poster presentation, Bristol Hub for Gambling Harms Research – International Interdisciplinary Colloquium (2025) - This poster presents interim findings from a realist review examining how public health laws and regulations intended to reduce gambling harms operate in practice. Drawing on evidence from multiple disciplines, the review identifies interventions that reduce gambling behaviour, expenditure, and time spent gambling, while also highlighting unintended and inequitable effects for certain groups. The work explores how interventions function across different levels of intrusiveness and maps findings onto the Nuffield Intervention Ladder, noting the need for adaptation for gambling-related public health interventions.',
    links: [],
    date: '2025-02-01',
    type: 'Event'
  },
  {
    id: 'd6',
    title: 'WP1 Public Engagement Workshops — Interventional Public Health Laws & Regulations',
    summary: 'Three public engagement workshops were completed as part of Work Package 1: 1. Initial synthesis of findings to co-produce preliminary interpretations with stakeholders. 2. Follow-up discussion exploring which laws are working well, which are not, and how they could be strengthened. 3. Data synthesis and planning session outlining next analytical steps and evidence integration. These sessions support the contextual interpretation of evidence on legal and regulatory interventions.',
    links: [],
    date: '2024-11-15',
    type: 'Event'
  },
  {
    id: 'd7',
    title: 'Guest Lecture — Health Improvement Module, MPhil Public Health (University of Birmingham)',
    summary: 'A lecture titled “Gambling as a Public Health Concern” was delivered to the Master of Public Health cohort, covering epidemiology, regulatory frameworks, and the public health implications of gambling harms.',
    links: [],
    date: '2024-10-20',
    type: 'Event'
  },
  {
    id: 'd8',
    title: 'Developing an equitable public health law approach to gambling harms',
    summary: 'Workshop presentation by Kate Bedford (Birmingham Law School) and Joht Singh Chandan (Institute of Applied Health Research, University of Birmingham) — Health and Care Law: Addressing Health and Care Inequalities Workshop, Birmingham Law School (13 June 2024 / 13 November 2025) - This presentation outlined the case for a public health law framework for gambling harms, with emphasis on equity, regulatory design, and legal approaches to reducing health inequalities.',
    links: [],
    date: '2024-06-13',
    type: 'Event'
  },
  {
    id: 'd9',
    title: 'Gambling law and public health: the equalities angles',
    summary: 'Conference presentation by Kate Bedford, Professor of Law and Political Economy, University of Birmingham — Workshop on “Reflections on Global Health Law, Public Health and Human Rights: From a time of turbulence to a more responsive future?” - This presentation examined how gambling regulation intersects with public health and equality considerations in both UK and global contexts.',
    links: [],
    date: '2024-04-01',
    type: 'Event'
  }
];
